version: '3.8'
services:
  php-fpm:
    image: ghcr.io/adefilippi/dev-php7.4-fpm:latest
    environment:
      FPM_UID: ${FPM_UID:-83}
      FPM_GID: ${FPM_GID:-83}
    depends_on:
      - database
    volumes:
      - ./:/var/www/

  nginx:
    image: ghcr.io/syneido/dev-nginx:latest
    environment:
      FPM_ENTRYPOINT: index
      PHP_FPM_CONTAINER: php-fpm
      NGINX_PROJECT: local
      NGINX_HOST: mysuzuki.fr
      NGINX_ROOT_DIR: public
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=api_commercial_info
      - POSTGRES_USER=api_commercial_info
      - POSTGRES_PASSWORD=api_commercial_info
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  build-php:
    image: ghcr.io/adefilippi/build-php7.4:latest
    volumes:
      - ./:/app/

volumes:
  db_data:

    #buildx build --tag ghcr.io/adefilippi/dev-php7.4-fpm:latest  --file ./Dockerfile-fpm --push ./