vich_uploader:
    db_driver: orm

    mappings:
        attachment:
            uri_prefix: /upload/attachment
            upload_destination: '%kernel.project_dir%/public/upload/attachment'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        rules:
            uri_prefix: /upload/rules
            upload_destination: '%kernel.project_dir%/public/upload/rules'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
