export const ActionTypes = {
    SET_INFORMATION_FROM_VIN: "SIGN_UP_PROCESS_SERIAL_SET_INFORMATION_FROM_VIN",
    SET_ERROR_FROM_VIN: "SIGN_UP_PROCESS_SERIAL_ERROR",
    SET_LOADING: "SIGN_UP_PROCESS_SET_LOADING"
};
