"https://api.{default}/":
    type: upstream
    upstream: "backend:http"

"https://www.{default}/":
    type: upstream
    upstream: "frontend:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"