export const ActionTypes = {
  SET_MAINTENANCES: "USER_SET_MAINTENANCES",
  ADD_MAINTENANCE: "USER_ADD_MAINTENANCE",
  UPDATE_MAINTENANCE: "USER_UPDATE_MAINTENANCE",
  REMOVE_MAINTENANCE: "USER_REMOVE_MAINTENANCE",
};
