export const ActionTypes = {
    SET_ARTICLES: "SET_ARTICLES",
    SET_NEWS: "SET_NEWS",
    SET_ASSOCIATED_ARTICLES: "SET_ASSOCIATED_ARTICLES",
    SET_ARTICLE: "SET_ARTICLE",
    RESET_ARTICLES: "RESET_ARTICLES",
    RESET_NEWS: "RESET_NEWS",
};
