export const ActionTypes = {
    SET_ACCOUNT: "SIGN_UP_PROCESS_CREDENTIAL_SET_ACCOUNT",
    SET_ERROR: "SIGN_UP_PROCESS_CREDENTIAL_SET_ERROR",
    SET_LOADING: "SIGN_UP_PROCESS_CREDENTIAL_SET_LOADING"
};
